#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
PGID/PUID
-------------------------------------'
echo "
User PUID:    $(id -u abc)
User PGID:    $(id -g abc)
-------------------------------------
"
chown -R abc:abc /app
chown -R abc:abc /config
chown -R abc:abc /download
chown -R abc:abc /watch

chmod 777 /app/bottorrent.py 
